version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: trading_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: trading_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data: